---
title: "Horas de trabajo"
output:
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    orientation: rows
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

# Define archivo de trabajo
input_file <- here::here("horas_trabajo.csv")

Sys.setlocale(category = "LC_ALL", locale = "es_ES.UTF-8")

# Carga de librerías
library(dplyr)
library(lubridate) #manejo de fechas
library(plotly)
library(flexdashboard)
library(janitor)

library(zoo) #series de tiempo
library(RcppRoll)
library(viridis)

options("lubridate.week.start" = 1) # Establece lunes como inicio de semana

# Carga de datos ------------------------------------------------------------

df <-
  data.table::fread(input_file, sep = ";") |>
  clean_names() |>
  mutate(
    inicio = inicio |> as.POSIXct(format = "%d/%m/%Y %H:%M:%S"),
    fin = fin |> as.POSIXct(format = "%d/%m/%Y %H:%M:%S")
  )

# Funciones -----------------------------------------------------------------

# Agrupa base de datos en trabajos en cada día
group_by_work <- function(df) {
  df <- df |>
    mutate(fecha = date(inicio)) |>
    group_by(trabajo, fecha) |>
    summarise(mins = sum(difftime(fin, inicio, units = "min"))) |>
    mutate(
      dia = wday(fecha, label = TRUE, abbr = FALSE),
      horas = (mins / 60) |> as.numeric(),
      pomodoros = (mins / 25) |> round() |> as.numeric(),
    )
}

# Agrupa dataframe por día (requiere base group by work)
group_by_day <- function(df) {
  df <- df |>
    group_by(fecha) |>
    summarise(
      mins = sum(mins),
      pomodoros = sum(pomodoros),
      horas = sum(horas)
    ) |>
    mutate(dia = wday(fecha, label = TRUE, abbr = FALSE),
           semana = isoweek(fecha))
}

# Genera totales (requiere base group_by_day)
get_totals <- function(df, date_start, date_end) {
  df <- df |>
    filter(fecha >= date_start & fecha <= date_end) |>
    summarise(
      mins = sum(mins),
      pomodoros = sum(pomodoros),
      horas = sum(horas)
    )
}

# Crea un gráfico de barras
plot_barras <- \(df, x, y, fill = !!x) {
  x <- enquo(x)
  y <- enquo(y)
  fill <- enquo(fill)
  
  ggplot(df, aes(!!x, !!y, fill = !!fill)) +
    theme_minimal() +
    viridis::scale_fill_viridis(discrete = TRUE, alpha = 0.6) +
    geom_col(color = "black", size = 0.3) +
    labs(x = element_blank(),
         y = element_blank(),
         title = element_blank()) +
    theme(legend.position = "none")
}
# # Obtiene los datos de la semana
# semana <- diario |>
#   filter(
#     year(fecha) == year(today()) &
#     isoweek(fecha) == isoweek(today())
#     ) |>
#   summarise(
#     mins = sum(mins),
#     pomodoros = sum(pomodoros),
#     horas = sum(horas)
#   )
# 
# # Obtiene datos del día
# dia <- diario |>
#   filter(fecha == today()) |>
#   summarise(mins = sum(mins), pomodoros = sum(pomodoros)) |>
#   mutate(horas = (mins / 60) |> as.numeric())

# Variables -----------------------------------------------------------------

week_start <- floor_date(today(), "week")
week_end <- ceiling_date(today(), "week")

total_semana <- df |> 
  group_by_work () |> 
  group_by_day() |> 
  get_totals(week_start, week_end)

total_dia <- df |> 
  group_by_work() |> 
  group_by_day() |> 
  get_totals(today(), today())
```

## Cabecera

### Horas de trabajo en la semana

```{r}
  gauge(
    round(total_semana$horas),
    min = 0,
    max = 40,
    symbol = "h",
    gaugeSectors(
      warning = c(0, 20),
      success = c(20, 30),
      danger = c(30, 40)
    ))
```

### Pomodoros en la semana

```{r}
  gauge(
    round(total_semana$pomodoros),
    min = 0,
    max = 80,
    symbol = "🍅",
    gaugeSectors(
      warning = c(0, 40),
      success = c(40, 60),
      danger = c(60, 80)
    ))
```


### Horas de trabajo en el día

```{r}
  gauge(
    round(total_dia$horas),
    min = 0,
    max = 8,
    symbol = "h",
    gaugeSectors(
      warning = c(0, 5),
      success = c(5, 6),
      danger = c(6, 8)
    )
  )
```

### Pomodoro de trabajo en el día

```{r}
  gauge(
    round(total_dia$pomodoros),
    min = 0,
    max = 16,
    symbol = "🍅",
    gaugeSectors(
      warning = c(0, 8),
      success = c(8, 12),
      danger = c(12, 16)
    )
  )
```
## Todos los días

### Pomodoros
```{r fig.width=10, fig.height=3}
plot_pomodoros <- df |> 
  group_by_work() |> 
  group_by_day() |> 
  filter(fecha >= today() - 90) |> 
  plot_barras(fecha, pomodoros, pomodoros) +
  viridis::scale_fill_viridis(alpha = 0.6) +
    geom_hline(yintercept = 8,
             linetype = "dashed",
             color = "green3") +
  geom_hline(yintercept = 12,
             linetype = "dashed",
             color = "red")
  
ggplotly(plot_pomodoros )
```

## Horas por trabajo

### Horas en el último mes

```{r}
hmes.plot <- trabajos |>
  filter(
    year(fecha) == year(today()) &
    month(fecha) == month(today())
    ) |>
  group_by(trabajo) |>
  summarize(pomodoros = sum(pomodoros)) |>
  barras.plot(reorder(trabajo, pomodoros), pomodoros) +
  coord_flip()

ggplotly(hmes.plot)
```

### En la última semana

```{r}
hsem.plot <- df |>
  group_by_work() |>
  filter(fecha >= week_start & fecha <= week_end) |>
  group_by(trabajo) |>
  summarize(pomodoros = sum(pomodoros)) |>
  plot_barras(reorder(trabajo, pomodoros), pomodoros) + coord_flip()

ggplotly(hsem.plot)
```

## Horas por día

### Promedio de trabajo por día:

```{r}
promdia.plot <- diario |>
  group_by(dia, semana) |>
  summarise(horas = sum(horas)) |>
  group_by(dia) |>
  summarise(horas = mean(horas) |> round(2)) |>
  barras.plot(dia, horas)
ggplotly(promdia.plot)
```

### Trabajo por día en la última semana:

```{r}
hdia.plot <- diario |>
  filter(isoweek(fecha) == today() |> isoweek()) |>
  group_by(dia) |>
  summarise(horas = sum(horas)) |>
  barras.plot(dia, horas)
ggplotly(hdia.plot)
```
